language: ruby
rvm:
  - 2.1.1
install: bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - touch config/database.yml
before_script:
  - cp config/database.yml.travis config/database.yml
script: bundle exec rspec
script: bundle exec teaspoon